datasets:
  vizwiz:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /mnt/data/vizwiz/annotations/train.json
          storage: vizwiz/annotations/train.json
        val:
          url: /mnt/data/vizwiz/annotations/val.json
          storage: vizwiz/annotations/val.json
      images:
          storage: vizwiz/images/
