datasets:
  text_vqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /mnt/data/textvqa/annotations/train.json
          storage: textvqa/annotations/train.json
        val:
          url: /mnt/data/textvqa/annotations/val.json
          storage: textvqa/annotations/val.json
      images:
          storage: textvqa/images/
    prompt: "OCR tokens: {} Question: {} Short answer:"
