datasets:
  science_qa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /mnt/data/scienceqa/annotations/train_problems.json
          storage: scienceqa/annotations/train_problems.json
        val:
          url: /mnt/data/scienceqa/annotations/val_problems.json
          storage: scienceqa/annotations/val_problems.json
        test:
          url: /mnt/data/scienceqa/annotations/test_problems.json
          storage: scienceqa/annotations/test_problems.json
      images:
          storage: scienceqa/images/
